export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  BATTERY_EMPTY: 'BATTERY_EMPTY',
  RATE_LIMITED: 'RATE_LIMITED',

  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_BAD_RESPONSE: 'PROVIDER_BAD_RESPONSE',

  INFERENCE_FAILED: 'INFERENCE_FAILED',
  MEMORY_PROCESSING_FAILED: 'MEMORY_PROCESSING_FAILED',

  VOICE_CALL_DISCONNECTED: 'VOICE_CALL_DISCONNECTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
